# project object to be store in the
type: object
properties:
  id:
    description: the unique identifier of the project created by a company.
    type: string
    format: cuid
    readOnly: true
  type:
    description: the type of the project created by a company.
    type: string
    format: array
    items:
      type: string
      required:
        - INITIAL_INSPECTION
        - EXTERNAL_INSPECTION
        - AUTO_EVALUATION
  company_id:
    description: the companies ID to which the project belongs to.
    type: string
    format: cuid
    example: "AQA9CNo0cXNLt6sZp5Uc5P0"
  title:
    description: the title of the project
    type: string
    example: "internal inspection"
  description:
    description: the description of the project
    type: string
    example: "internal inspection"
  sector_activity:
    description: the sector of activity of the project
    type: string
    example: "engineering"
  country:
    type: string
    format: array

    description: The countries where the project will take place
    example: "Cameroon"
  city:
    type: string
    format: array
    description: The city where the project will take place
    items:
      type: string
    example: ["Douala", "buea", "yaounde"]
  status:
    type: string
    description: The status of the project
    example: ["active", "draft", "archived"]
    enum:
      - ARCHIVED
      - DRAFT
      - ACTIVE
      - INACTIVE
  start_date:
    description: The start date of the project
    type: string
    format: date-time
    example: "2022-10-10T00:00:00.000Z"
  end_date:
    description: The end date of the project
    type: string
    format: date-time
    example: "2022-10-10T00:00:00.000Z"
  project_structure:
    description: The former structure of the project
    type: string
    format: object
    example:
      {
        title: string,
        description: string,
        start_date: string,
        end_date: string,
        status: string,
        ...,
      }
  archived:
    type: boolean
    description: To set the project as archived.
  draft:
    type: boolean
    description: set project as draft.
  created_at:
    type: string
    format: date-time
    description: The date and time when the project was created.
    example: "2022-10-10T00:00:00.000Z"
  updated_at:
    type: string
    format: date-time
    description: The date and time when the project was updated.
    example: "2022-10-10T00:00:00.000Z"
  deleted_at:
    type: string
    format: date-time
    description: The date and time when the project was deleted.
  slug:
    type: string
    description: the slug of the project title
    example: "internal_inspection_for_local_farmers"
  archived_at:
    type: string
    format: date-time
    example: "2022-10-10T00:00:00.000Z"
  draft_at:
    type: string
    format: date-time
    example: "2022-10-10T00:00:00.000Z"
  deployed_at:
    type: string
    format: date-time
    example: "2022-10-10T00:00:00.000Z"
