#the participant of the training session
type: object
properties:
  id:
    type: string
    format: cuid
    readOnly: true
    description: "The unique Id of the participant."
  first_name:
    type: string
    description: "first name of the participant"
  last_name:
    type: string
    description: "last name of the participant"
  email:
    type: string
    description: "email of the participant"

  signature:
    type: string
    description: "To hold the digital the signature of the participant"
  role:
    type: string
    description: To Specify the role of the participant
    example: "Farmer, Trainer"
  training_id:
    type: string
    format: cuid
    description: the company id of the training
    example: 1jssbbjsbjsbjs221878dd817dd87sd
  phone:
    type: string
    description: To Specify the phone number of the participant
  training_picture_urls:
    type: string
    format: array
    description: the images of the training
    example: ["https://senima.com/wp-content/uploads/2022/01/gold.png"]
  report_url:
    type: string
    description: To specify the report of the training
    example: "https://senima.com/wp-content/uploads/2022/01/report.pdf"
  trainer_proof_of_competency:
    type: string
    format: array
    description: the training proof of competency of the trainer.
  created_at:
    type: string
    format: date-time
    example: "2020-01-01T00:00:00Z"
    description: "the date and time when the participant was created"
  updated_at:
    type: string
    format: date-time
    example: "2020-01-01T00:00:00Z"
    description: "the date and time when the participant was updated"
