type: object
required:
  - training_id
  - session_date
  - location
  - trainer_id
  - max_participants
properties:
  id:
    type: string
    format: cuid
    readOnly: true
    description: "The unique ID of the training session"
    example: "clh1234567890abcdef"
  training_id:
    type: string
    format: cuid
    description: "The ID of the training this session belongs to"
    example: "clh1234567890abcdef"
  session_date:
    type: string
    format: date
    description: "The date of the training session"
    example: "2024-01-15"
  start_time:
    type: string
    pattern: "^([0-1][0-9]|2[0-3]):[0-5][0-9]$"
    description: "Start time of the session (24-hour format)"
    example: "09:00"
  end_time:
    type: string
    pattern: "^([0-1][0-9]|2[0-3]):[0-5][0-9]$"
    description: "End time of the session (24-hour format)"
    example: "17:00"
  location:
    type: string
    description: "Location where the session will be held"
    example: "Community Center"
  trainer_id:
    type: string
    format: cuid
    description: "The ID of the trainer conducting the session"
    example: "clh1234567890abcdef"
  max_participants:
    type: integer
    minimum: 1
    description: "Maximum number of participants allowed"
    example: 30
  current_participants:
    type: integer
    minimum: 0
    description: "Current number of participants registered"
    example: 25
  status:
    type: string
    enum: ["scheduled", "in-progress", "completed", "cancelled"]
    description: "Current status of the session"
    example: "scheduled"
  created_at:
    type: string
    format: date-time
    readOnly: true
    description: "When the session was created"
    example: "2024-01-15T10:30:00Z"
  updated_at:
    type: string
    format: date-time
    readOnly: true
    description: "When the session was last updated"
    example: "2024-01-15T10:30:00Z"
