#create a training object
type: object
properties:
  id:
    description: the unique identifier for the training object
    type: string
    format: cuid
    readOnly: true
  theme:
    type: string
    description: the theme for the training programming
  title:
    type: string
    description: the title for the training
  content:
    type: string
    description: the content of the training
  date:
    type: string
    format: date-time
  locality:
    type: string
    description: the locality of the training
  company_id:
    type: string
    format: cuid
    description: the company id of the training
    example: 1jssbbjsbjsbjs221878dd817dd87sd
  traning_report:
    type: string
    description: the report of the training
  training_picture_url:
    type: string
    format: array
    description: the images of the training
    example: ["https://senima.com/wp-content/uploads/2022/01/gold.png"]
