# get training by ID
get:
  tags:
    - 🎓 Training
  summary: Get training by ID
  description: |
    Retrieve a specific training by its ID.
  operationId: getTrainingById
  security:
    - BearerAuth: []
  parameters:
    - name: training_id
      in: path
      required: true
      description: ID of the training to retrieve
      schema:
        type: string
        format: cuid
  responses:
    "200":
      description: List of trainings retrieved successfully
      content:
        application/json:
          schema:
            $ref: "../../components/schemas/training.yaml"
    "400":
      $ref: "../../components/responses/ValidationError.yaml"
    "401":
      $ref: "../../components/responses/UnauthorizedError.yaml"
    "403":
      $ref: "../../components/responses/ForbiddenError.yaml"
    "429":
      $ref: "../../components/responses/RateLimitError.yaml"
    "500":
      $ref: "../../components/responses/ServerError.yaml"

# update training
put:
  tags:
    - 🎓 Training
  summary: Update a training
  description: Update an existing training
  operationId: updateTraining
  security:
    - BearerAuth: []
  parameters:
    - name: training_id
      in: path
      required: true
      description: ID of the training to update
      schema:
        type: string
        format: cuid
  requestBody:
    required: true
    content:
      application/json:
        schema:
          $ref: "../../components/schemas/training.yaml"
  responses:
    "200":
      description: Training updated successfully
      content:
        application/json:
          schema:
            $ref: "../../components/schemas/training.yaml"
    "400":
      $ref: "../../components/responses/ValidationError.yaml"
    "401":
      $ref: "../../components/responses/UnauthorizedError.yaml"
    "403":
      $ref: "../../components/responses/ForbiddenError.yaml"
    "404":
      description: Training not found
      content:
        application/json:
          schema:
            type: object
            properties:
              error:
                type: string
                example: "Training Not Found"
              message:
                type: string
                example: "Training with the specified ID was not found"
              code:
                type: string
                example: "TRAINING_NOT_FOUND"
    "409":
      description: Update conflict
      content:
        application/json:
          schema:
            type: object
            properties:
              error:
                type: string
                example: "Update Conflict"
              message:
                type: string
                example: "Cannot update training in current state"
              code:
                type: string
                example: "UPDATE_CONFLICT"
    "500":
      $ref: "../../components/responses/ServerError.yaml"

# delete training
delete:
  tags:
    - 🎓 Training
  summary: Delete a training
  description: Delete an existing training
  operationId: deleteTraining
  security:
    - BearerAuth: []
  parameters:
    - name: training_id
      in: path
      required: true
      description: ID of the training to delete
      schema:
        type: string
        format: cuid
  responses:
    "204":
      description: Training deleted successfully
    "401":
      $ref: "../../components/responses/UnauthorizedError.yaml"
    "403":
      $ref: "../../components/responses/ForbiddenError.yaml"
    "404":
      description: Training not found
      content:
        application/json:
          schema:
            type: object
            properties:
              error:
                type: string
                example: "Training Not Found"
              message:
                type: string
                example: "Training with the specified ID was not found"
              code:
                type: string
                example: "TRAINING_NOT_FOUND"
    "500":
      $ref: "../../components/responses/ServerError.yaml"
