# create a training data
post:
  tags:
    - 🎓 Training
  summary: Create a new training
  description: Create a new training record
  operationId: createTraining
  security:
    - BearerAuth: []
  requestBody:
    required: true
    content:
      application/json:
        schema:
          $ref: "../../components/schemas/training.yaml"
  responses:
    "201":
      description: Training created successfully
      content:
        application/json:
          schema:
            $ref: "../../components/schemas/training.yaml"
    "400":
      $ref: "../../components/responses/ValidationError.yaml"
    "401":
      $ref: "../../components/responses/UnauthorizedError.yaml"
    "403":
      $ref: "../../components/responses/ForbiddenError.yaml"
    "409":
      description: Training already exists
      content:
        application/json:
          schema:
            type: object
            properties:
              error:
                type: string
                example: "Training Already Exists"
              message:
                type: string
                example: "A training with these parameters already exists"
              code:
                type: string
                example: "TRAINING_ALREADY_EXISTS"
    "500":
      $ref: "../../components/responses/ServerError.yaml"

# get all training data
get:
  tags:
    - 🎓 Training
  summary: List all trainings
  description: |
    Retrieve a list of all trainings.
    This endpoint supports pagination and filtering.
  operationId: listTrainings
  security:
    - BearerAuth: []
  parameters:
    - $ref: "../../components/parameters/PaginationLimit.yaml"
    - $ref: "../../components/parameters/PaginationOffset.yaml"
    - $ref: "../../components/parameters/CompanyId.yaml"
    - $ref: "../../components/parameters/DateRangeStart.yaml"
    - $ref: "../../components/parameters/DateRangeEnd.yaml"
  responses:
    "200":
      description: List of trainings retrieved successfully
      content:
        application/json:
          schema:
            type: object
            properties:
              data:
                type: array
                items:
                  $ref: "../../components/schemas/training.yaml"
              meta:
                type: object
                properties:
                  total:
                    type: integer
                    example: 100
                  page:
                    type: integer
                    example: 1
                  limit:
                    type: integer
                    example: 20
                  has_more:
                    type: boolean
                    example: true
    "400":
      $ref: "../../components/responses/ValidationError.yaml"
    "401":
      $ref: "../../components/responses/UnauthorizedError.yaml"
    "403":
      $ref: "../../components/responses/ForbiddenError.yaml"
    "429":
      $ref: "../../components/responses/RateLimitError.yaml"
    "500":
      $ref: "../../components/responses/ServerError.yaml"

# update training
put:
  tags:
    - 🎓 Training
  summary: Update a training
  description: Update an existing training
  operationId: updateTraining
  security:
    - BearerAuth: []
  parameters:
    - name: training_id
      in: path
      required: true
      description: ID of the training to update
      schema:
        type: string
        format: cuid
  requestBody:
    required: true
    content:
      application/json:
        schema:
          $ref: "../../components/schemas/training.yaml"
  responses:
    "200":
      description: Training updated successfully
      content:
        application/json:
          schema:
            $ref: "../../components/schemas/training.yaml"
    "400":
      $ref: "../../components/responses/ValidationError.yaml"
    "401":
      $ref: "../../components/responses/UnauthorizedError.yaml"
    "403":
      $ref: "../../components/responses/ForbiddenError.yaml"
    "404":
      description: Training not found
      content:
        application/json:
          schema:
            type: object
            properties:
              error:
                type: string
                example: "Training Not Found"
              message:
                type: string
                example: "Training with the specified ID was not found"
              code:
                type: string
                example: "TRAINING_NOT_FOUND"
    "409":
      description: Update conflict
      content:
        application/json:
          schema:
            type: object
            properties:
              error:
                type: string
                example: "Update Conflict"
              message:
                type: string
                example: "Cannot update training in current state"
              code:
                type: string
                example: "UPDATE_CONFLICT"
    "500":
      $ref: "../../components/responses/ServerError.yaml"

# delete training
delete:
  tags:
    - 🎓 Training
  summary: Delete a training
  description: Delete an existing training
  operationId: deleteTraining
  security:
    - BearerAuth: []
  parameters:
    - name: training_id
      in: path
      required: true
      description: ID of the training to delete
      schema:
        type: string
        format: cuid
  responses:
    "204":
      description: Training deleted successfully
    "401":
      $ref: "../../components/responses/UnauthorizedError.yaml"
    "403":
      $ref: "../../components/responses/ForbiddenError.yaml"
    "404":
      description: Training not found
      content:
        application/json:
          schema:
            type: object
            properties:
              error:
                type: string
                example: "Training Not Found"
              message:
                type: string
                example: "Training with the specified ID was not found"
              code:
                type: string
                example: "TRAINING_NOT_FOUND"
    "500":
      $ref: "../../components/responses/ServerError.yaml"
