get:
  tags:
    - 🎓 Training
  summary: List all training sessions
  description: |
    Retrieve a list of all training sessions.
    This endpoint supports pagination and filtering.
  operationId: listTrainingSessions
  parameters:
    - $ref: "../../components/parameters/PaginationLimit.yaml"
    - $ref: "../../components/parameters/PaginationOffset.yaml"
    - $ref: "../../components/parameters/CompanyId.yaml"
    - $ref: "../../components/parameters/DateRangeStart.yaml"
    - $ref: "../../components/parameters/DateRangeEnd.yaml"
  responses:
    "200":
      description: List of training sessions retrieved successfully
      content:
        application/json:
          schema:
            type: object
            properties:
              data:
                type: array
                items:
                  $ref: "../../components/schemas/training_session.yaml"
              meta:
                type: object
                properties:
                  total:
                    type: integer
                    example: 100
                  pages:
                    type: integer
                    example: 5
                  current_page:
                    type: integer
                    example: 1
                  per_page:
                    type: integer
                    example: 20
    "401":
      $ref: "../../components/responses/UnauthorizedError.yaml"
    "403":
      $ref: "../../components/responses/ForbiddenError.yaml"
    "500":
      $ref: "../../components/responses/ServerError.yaml"

post:
  tags:
    - 🎓 Training
  summary: Create a new training session
  description: Create a new training session for a training
  operationId: createTrainingSession
  requestBody:
    required: true
    content:
      application/json:
        schema:
          $ref: "../../components/schemas/training_session.yaml"
        examples:
          basic_session:
            summary: Basic training session
            description: Create training session with minimal information
            value:
              training_id: "clh1234567890abcdef"
              session_date: "2024-01-15"
              location: "Community Center"
              trainer_id: "clh1234567890abcdef"
              max_participants: 30
          detailed_session:
            summary: Detailed training session
            description: Create training session with all available information
            value:
              training_id: "clh1234567890abcdef"
              session_date: "2024-01-15"
              start_time: "09:00"
              end_time: "17:00"
              location: "Community Center"
              trainer_id: "clh1234567890abcdef"
              max_participants: 30
              status: "scheduled"
  responses:
    "201":
      description: Training session created successfully
      content:
        application/json:
          schema:
            $ref: "../../components/schemas/training_session.yaml"
    "400":
      $ref: "../../components/responses/ValidationError.yaml"
    "401":
      $ref: "../../components/responses/UnauthorizedError.yaml"
    "403":
      $ref: "../../components/responses/ForbiddenError.yaml"
    "409":
      description: Training session already exists
      content:
        application/json:
          schema:
            type: object
            properties:
              error:
                type: string
                example: "Conflict"
              message:
                type: string
                example: "Training session already exists"
              code:
                type: string
                example: "SESSION_EXISTS"
    "500":
      $ref: "../../components/responses/ServerError.yaml"

put:
  tags:
    - 🎓 Training
  summary: Update training session
  description: Update an existing training session
  operationId: updateTrainingSession
  requestBody:
    required: true
    content:
      application/json:
        schema:
          $ref: "../../components/schemas/training_session.yaml"
  parameters:
    - name: session_id
      in: path
      required: true
      description: ID of the training session to update
      schema:
        type: string
        format: cuid
        example: "clh1234567890abcdef"
  responses:
    "200":
      description: Training session updated successfully
      content:
        application/json:
          schema:
            $ref: "../../components/schemas/training_session.yaml"
    "400":
      $ref: "../../components/responses/ValidationError.yaml"
    "401":
      $ref: "../../components/responses/UnauthorizedError.yaml"
    "403":
      $ref: "../../components/responses/ForbiddenError.yaml"
    "404":
      description: Training session not found
      content:
        application/json:
          schema:
            type: object
            properties:
              error:
                type: string
                example: "Not Found"
              message:
                type: string
                example: "Training session not found"
              code:
                type: string
                example: "SESSION_NOT_FOUND"
    "500":
      $ref: "../../components/responses/ServerError.yaml"
